game:
  expire-time: 3
scoreboard:
  game:
    title: "&eResourceRush"
    lines:
      - "&m&7---------------------"
      - ""
      - " &fYour name: &e{player_name}"
      - " "
      - " &fYour points: &e{points}"
      - ""
      - "&m&7---------------------"
blocksbreak-sound: ENTITY_PLAYER_LEVELUP
break-sound: true
broadcastStart:
  - "&m&7------------------------------"
  - ""
  - "     &eStarting... ResourceRush"
  - ""
  - "      &7Usage: &e/collect join"
  - ""
  - "&m&7------------------------------"
winner-message:
  - "&m&7------------------------------"
  - ""
  - "       &fWinner: &7{winnerName} &rpoints: &e{winnerPoints}"
  - ""
  - "&m&7------------------------------"